[package]
name = "desmos_music"
authors = ["Ruel Nathaniel Alarcon"]
description = "A Rust-based CLI tool for converting MIDI files into formulas for Desmos."
version = "0.2.0"
edition = "2021"

[dependencies]
midly = "0.5"
clipboard = "0.5"
clap = { version = "4.5", features = ["derive"] }